services:
  neo4j:
    profiles: ["db"]  # only starts if you pass --profile db

  api:
    depends_on: []    # ensure api doesn't require the neo4j service
    environment:
      NEO4J_URI: "${NEO4J_URI:-bolt://host.docker.internal:7687}"
      NEO4J_USER: "${NEO4J_USER:-neo4j}"
      NEO4J_PASS: "${NEO4J_PASS:-${NEO4J_PASSWORD}}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    environment:
      NEO4J_URI: "${NEO4J_URI:-bolt://host.docker.internal:7687}"
      NEO4J_USER: "${NEO4J_USER:-neo4j}"
      NEO4J_PASS: "${NEO4J_PASS:-${NEO4J_PASSWORD}}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ingest:
    environment:
      NEO4J_URI: "${NEO4J_URI:-bolt://host.docker.internal:7687}"
      NEO4J_USER: "${NEO4J_USER:-neo4j}"
      # NEO4J_PASS can be set in .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
