services:
  neo4j:
    image: neo4j:5.20.0
    container_name: lineage_neo4j
    restart: unless-stopped
    ports:
    - ${NEO4J_HTTP_PORT:-7474}:7474
    - ${NEO4J_BOLT_PORT:-7687}:7687
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_server_memory_heap_initial__size: 1G
      NEO4J_server_memory_heap_max__size: 2G
    volumes:
    - ./neo4j/data:/data
    - ./neo4j/import:/import
    - ./neo4j/logs:/logs
  api:
    build: ./api
    container_name: lineage_api
    restart: unless-stopped
    environment:
      NEO4J_URI: ${NEO4J_URI:-bolt://neo4j:7687}
      NEO4J_USER: neo4j
      NEO4J_PASS: ${NEO4J_PASSWORD}
      API_PORT: ${API_PORT:-8000}
    ports:
    - ${API_PORT:-8000}:8000
    extra_hosts:
      - "neo4j:host-gateway"
    - host.docker.internal:host-gateway
  web:
    build: ./web
    container_name: lineage_web
    restart: unless-stopped
    depends_on:
    - api
    ports:
    - ${WEB_PORT:-3000}:80

  ingest:
    build: ./scanner
    container_name: lineage_ingest
    profiles: ["ingest"]
    depends_on: []
    environment:
      NEO4J_URI: "${NEO4J_URI:-bolt://neo4j:7687}"
      NEO4J_USER: "${NEO4J_USER:-neo4j}"
      NEO4J_PASS: "${NEO4J_PASS:-${NEO4J_PASSWORD}}"
    command: ["ingest", "--path", "/scan", "--conn", "${SCANNER_CONN:-demo_pg}", "--connections", "/connections.yaml"]
    volumes:
      - "${SCAN_PATH:-./sample-repo}:/scan:ro"
      - "./scanner/connections.yaml:/connections.yaml:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "neo4j:host-gateway"

  queue:
    build: ./queue/api
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9000/healthz || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: lineage_queue
    restart: unless-stopped
    environment:
      API_PORT: "${QUEUE_API_PORT:-9000}"
      DB_PATH: "/data/queue.db"
      BACKUP_DIR: "/backups"
      GITHUB_WEBHOOK_SECRET: "${GITHUB_WEBHOOK_SECRET:-}"
    volumes:
      - ./queue/data:/data
      - ./queue/backups:/backups
    ports:
      - "${QUEUE_API_PORT:-9000}:9000"

  worker:
    build: ./queue/worker
    ports:
      - "${WORKER_METRICS_PORT:-9100}:9100"
    container_name: lineage_worker
    restart: unless-stopped
    depends_on: []
    environment:
      DB_PATH: "/data/queue.db"
      POLL_INTERVAL: "3"
      NEO4J_URI: "${NEO4J_URI:-bolt://neo4j:7687}"
      NEO4J_USER: "${NEO4J_USER:-neo4j}"
      NEO4J_PASS: "${NEO4J_PASS:-${NEO4J_PASSWORD}}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "neo4j:host-gateway"
    volumes:
      - ./queue/data:/data
      - ./queue/backups:/backups
      - ./scanner:/scanner:ro
      - ./sample-repo:/scan:ro
