services:
  # Mark Neo4j container as optional (started only with: --profile db)
  neo4j:
    profiles: ["db"]

  api:
    environment:
      # Default to local host's Neo4j when this override is used
      NEO4J_URI: "${NEO4J_URI:-bolt://host.docker.internal:7687}"
      NEO4J_USER: "${NEO4J_USER:-neo4j}"
      # API will fall back to NEO4J_PASSWORD if NEO4J_PASS is unset
      # set NEO4J_PASS here if your local DB uses a different password
      # NEO4J_PASS: "your-local-neo4j-password"
    extra_hosts:
      - "neo4j:host-gateway"
      - "host.docker.internal:host-gateway"
