version: "3.9"
services:
  neo4j:
    image: neo4j:${NEO4J_IMAGE_TAG}
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./loaders/neo4j/cypher:/cypher:ro
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USERNAME} -p ${NEO4J_PASSWORD} 'RETURN 1' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 30

  neo4j-loader:
    build: ./loaders/neo4j
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USERNAME}
      - NEO4J_PASS=${NEO4J_PASSWORD}
      - NORMALIZED_ROOT=/workspace/normalized
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./data/normalized:/workspace/normalized:ro
    command: ["/bin/bash","-lc","/app/entrypoint.sh"]

  tigergraph:
    image: tigergraph/tigergraph:${TG_IMAGE_TAG}
    environment:
      - USER=${TG_USERNAME}
      - PASSWORD=${TG_PASSWORD}
    ports:
      - "${TG_RESTPP_PORT}:9000"
      - "${TG_GSQL_PORT}:14240"
    volumes:
      - ./loaders/tigergraph/gsql:/gsql:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:9000/echo > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 60

  tg-loader:
    build: ./loaders/tigergraph
    depends_on:
      tigergraph:
        condition: service_healthy
    environment:
      - TG_HOST=http://tigergraph:9000
      - TG_GRAPH=LineageGraph
      - TG_USERNAME=${TG_USERNAME}
      - TG_PASSWORD=${TG_PASSWORD}
      - NORMALIZED_ROOT=/workspace/normalized
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./data/normalized:/workspace/normalized:ro
    command: ["/bin/bash","-lc","/app/entrypoint.sh"]

  compare:
    build: ./compare
    depends_on:
      neo4j:
        condition: service_healthy
      tigergraph:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USERNAME}
      - NEO4J_PASS=${NEO4J_PASSWORD}
      - TG_HOST=http://tigergraph:9000
      - TG_GRAPH=LineageGraph
      - TG_USERNAME=${TG_USERNAME}
      - TG_PASSWORD=${TG_PASSWORD}
    volumes:
      - ./data/output:/workspace/output
    command: ["/bin/bash","-lc","python /app/compare_lineage.py --out /workspace/output"]

networks: { default: { name: ${STACK_NETWORK} } }
